# Generated by Django 5.0 on 2025-04-28 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasteCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория вкуса',
                'verbose_name_plural': 'Категории вкусов',
                'db_table': 'app_tastecategories',
            },
        ),
    ]
