version: '3.9'

#volumes:
#  mysql_data:

services:
  mysql:
    image: mysql  # Зафиксирована версия
    container_name: local-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=inHookah
      - MYSQL_DATABASE=inHookah
      - MYSQL_USER=inHookah
      - MYSQL_PASSWORD=inHookah
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
