# Generated by Django 5.0 on 2025-04-28 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tobaccos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taste', models.CharField(blank=True, default=None, max_length=200, verbose_name='Вкус')),
                ('image', models.ImageField(blank=True, default=None, upload_to='')),
                ('tobacco_strength', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='0', max_length=2, verbose_name='Крепость')),
                ('tobacco_resistance', models.CharField(choices=[('-', ''), ('low', 'низкая'), ('middle', 'средняя'), ('high', 'высокая')], default='-', max_length=15, verbose_name='Теплостойкость')),
                ('tobacco_smokiness', models.CharField(choices=[('-', ''), ('low', 'низкая'), ('middle', 'средняя'), ('high', 'высокая')], default='-', max_length=15, verbose_name='Дымность')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание ингредиента')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tobacco', to='manufacturers.manufacturers', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Табак',
                'verbose_name_plural': 'Табаки',
                'db_table': 'app_tobaccos',
            },
        ),
    ]
