# Generated by Django 5.0 on 2025-04-28 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bowls',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200, verbose_name='Тип чаши')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
                ('howTo', models.TextField(blank=True, default=None, verbose_name='Инструкция')),
                ('image', models.ImageField(blank=True, default=None, upload_to='')),
            ],
            options={
                'verbose_name': 'Чаша',
                'verbose_name_plural': 'Чаши',
                'db_table': 'app_bowls',
            },
        ),
    ]
